apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tg-get
  name: tg-get
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-get
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tg-get
    spec:
      containers:
        - image: tg-get
          name: tg-get
          resources: {}
status: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tg-get
  name: tg-get
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: tg-get
  type: ClusterIP
status:
  loadBalancer: {}
